# Generated by Django 5.1.4 on 2024-12-23 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nomi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Turlar ',
                'verbose_name_plural': 'Turlar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('description', models.TextField(default="Ma'lumot qo'shilmadi.", verbose_name='Tavsifi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('count', models.IntegerField(default=0, verbose_name='Soni')),
                ('published', models.BooleanField(default=False, verbose_name='Nashr etilgan')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.types', verbose_name='Turi')),
            ],
            options={
                'verbose_name': 'Gullar ',
                'verbose_name_plural': 'Gullar',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Gul',
        ),
        migrations.DeleteModel(
            name='Tur',
        ),
    ]
